(function($){Drupal.behaviors.devel={attach:function(context,settings){$(".krumo-footnote .krumo-call").once().before('<img style="vertical-align: middle;" title="Click to expand. Double-click to show path." src="'+settings.basePath+'misc/help.png"/>');var krumo_name=[];var krumo_type=[];function krumo_traverse(el){krumo_name.push($(el).html());krumo_type.push($(el).siblings("em").html().match(/\w*/)[0]);if($(el).closest(".krumo-nest").length>0)krumo_traverse($(el).closest(".krumo-nest").prev().find(".krumo-name"))}
$(".krumo-child > div:first-child",context).dblclick(function(e){if($(this).find("> .krumo-php-path").length>0)$(this).find("> .krumo-php-path").remove();else{krumo_traverse($(this).find("> a.krumo-name"));var krumo_path_string="";for(var i=krumo_name.length-1;i>=0;--i){if(krumo_name.length-1==i)krumo_path_string+="$"+krumo_name[i];if(typeof krumo_name[i-1]!=="undefined"){if(krumo_type[i]=="Array"){krumo_path_string+="[";if(!/^\d*$/.test(krumo_name[i-1]))krumo_path_string+="'";krumo_path_string+=
krumo_name[i-1];if(!/^\d*$/.test(krumo_name[i-1]))krumo_path_string+="'";krumo_path_string+="]"}if(krumo_type[i]=="Object")krumo_path_string+="->"+krumo_name[i-1]}}$(this).append('<div class="krumo-php-path" style="font-family: Courier, monospace; font-weight: bold;">'+krumo_path_string+"</div>");krumo_name=[];krumo_type=[]}})}}})(jQuery);;
(function($){Drupal.behaviors.textarea={attach:function(context,settings){$(".form-textarea-wrapper.resizable",context).once("textarea",function(){var staticOffset=null;var textarea=$(this).addClass("resizable-textarea").find("textarea");var grippie=$('<div class="grippie"></div>').mousedown(startDrag);grippie.insertAfter(textarea);function startDrag(e){staticOffset=textarea.height()-e.pageY;textarea.css("opacity",.25);$(document).mousemove(performDrag).mouseup(endDrag);return false}function performDrag(e){textarea.height(Math.max(32,
staticOffset+e.pageY)+"px");return false}function endDrag(e){$(document).unbind("mousemove",performDrag).unbind("mouseup",endDrag);textarea.css("opacity",1)}})}}})(jQuery);;
(function($){Drupal.behaviors.tokenTree={attach:function(context,settings){$("table.token-tree",context).once("token-tree",function(){$(this).treeTable()})}};Drupal.behaviors.tokenDialog={attach:function(context,settings){$("a.token-dialog",context).once("token-dialog").click(function(){var url=$(this).attr("href");var dialog=$('<div style="display: none" class="loading">'+Drupal.t("Loading token browser...")+"</div>").appendTo("body");var data={};data["ajax_page_state[theme]"]=Drupal.settings.ajaxPageState.theme;
data["ajax_page_state[theme_token]"]=Drupal.settings.ajaxPageState.theme_token;dialog.dialog({title:$(this).attr("title")||Drupal.t("Available tokens"),width:700,close:function(event,ui){dialog.remove()}});dialog.load(url,data,function(responseText,textStatus,XMLHttpRequest){dialog.removeClass("loading")});return false})}};Drupal.behaviors.tokenInsert={attach:function(context,settings){$('textarea, input[type="text"]',context).focus(function(){Drupal.settings.tokenFocusedField=this});$(".token-click-insert .token-key",
context).once("token-click-insert",function(){var newThis=$('<a href="javascript:void(0);" title="'+Drupal.t("Insert this token into your form")+'">'+$(this).html()+"</a>").click(function(){if(typeof Drupal.settings.tokenFocusedField=="undefined")alert(Drupal.t("First click a text field to insert your tokens into."));else{var myField=Drupal.settings.tokenFocusedField;var myValue=$(this).text();if(document.selection){myField.focus();sel=document.selection.createRange();sel.text=myValue}else if(myField.selectionStart||
myField.selectionStart=="0"){var startPos=myField.selectionStart;var endPos=myField.selectionEnd;myField.value=myField.value.substring(0,startPos)+myValue+myField.value.substring(endPos,myField.value.length)}else myField.value+=myValue;$("html,body").animate({scrollTop:$(myField).offset().top},500)}return false});$(this).html(newThis)})}}})(jQuery);;
(function($){Drupal.toggleFieldset=function(fieldset){var $fieldset=$(fieldset);if($fieldset.is(".collapsed")){var $content=$("> .fieldset-wrapper",fieldset).hide();$fieldset.removeClass("collapsed").trigger({type:"collapsed",value:false}).find("> legend span.fieldset-legend-prefix").html(Drupal.t("Hide"));$content.slideDown({duration:"fast",easing:"linear",complete:function(){Drupal.collapseScrollIntoView(fieldset);fieldset.animating=false},step:function(){Drupal.collapseScrollIntoView(fieldset)}})}else{$fieldset.trigger({type:"collapsed",
value:true});$("> .fieldset-wrapper",fieldset).slideUp("fast",function(){$fieldset.addClass("collapsed").find("> legend span.fieldset-legend-prefix").html(Drupal.t("Show"));fieldset.animating=false})}};Drupal.collapseScrollIntoView=function(node){var h=document.documentElement.clientHeight||document.body.clientHeight||0;var offset=document.documentElement.scrollTop||document.body.scrollTop||0;var posY=$(node).offset().top;var fudge=55;if(posY+node.offsetHeight+fudge>h+offset)if(node.offsetHeight>
h)window.scrollTo(0,posY);else window.scrollTo(0,posY+node.offsetHeight-h+fudge)};Drupal.behaviors.collapse={attach:function(context,settings){$("fieldset.collapsible",context).once("collapse",function(){var $fieldset=$(this);var anchor=location.hash&&location.hash!="#"?", "+location.hash:"";if($fieldset.find(".error"+anchor).length)$fieldset.removeClass("collapsed");var summary=$('<span class="summary"></span>');$fieldset.bind("summaryUpdated",function(){var text=$.trim($fieldset.drupalGetSummary());
summary.html(text?" ("+text+")":"")}).trigger("summaryUpdated");var $legend=$("> legend .fieldset-legend",this);$('<span class="fieldset-legend-prefix element-invisible"></span>').append($fieldset.hasClass("collapsed")?Drupal.t("Show"):Drupal.t("Hide")).prependTo($legend).after(" ");var $link=$('<a class="fieldset-title" href="#"></a>').prepend($legend.contents()).appendTo($legend).click(function(){var fieldset=$fieldset.get(0);if(!fieldset.animating){fieldset.animating=true;Drupal.toggleFieldset(fieldset)}return false});
$legend.append(summary)})}}})(jQuery);;
